# Generated by Django 4.1.7 on 2023-03-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_data', '0003_alter_country_data_average_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_data',
            name='average_temperature_uncertainty',
            field=models.CharField(max_length=10),
        ),
    ]
