# Generated by Django 4.1.7 on 2023-03-24 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_data', '0004_alter_country_data_average_temperature_uncertainty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='city_data',
            name='city',
        ),
        migrations.RemoveField(
            model_name='city_data',
            name='country',
        ),
        migrations.RemoveField(
            model_name='country_data',
            name='country',
        ),
        migrations.RemoveField(
            model_name='state_data',
            name='country',
        ),
        migrations.RemoveField(
            model_name='state_data',
            name='state',
        ),
        migrations.AlterField(
            model_name='city_data',
            name='average_temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city_data',
            name='average_temperature_uncertainty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='country_data',
            name='average_temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='country_data',
            name='average_temperature_uncertainty',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('country_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='temperature_data.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('country_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='temperature_data.country')),
            ],
        ),
        migrations.AddField(
            model_name='city_data',
            name='city_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='temperature_data.city'),
        ),
        migrations.AddField(
            model_name='city_data',
            name='country_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='temperature_data.country'),
        ),
        migrations.AddField(
            model_name='country_data',
            name='country_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='temperature_data.country'),
        ),
        migrations.AddField(
            model_name='state_data',
            name='country_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='temperature_data.country'),
        ),
        migrations.AddField(
            model_name='state_data',
            name='state_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='temperature_data.state'),
        ),
    ]
