# Generated by Django 4.1.7 on 2023-03-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_data', '0005_country_remove_city_data_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_data',
            name='average_temperature',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='city_data',
            name='average_temperature_uncertainty',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='country_data',
            name='average_temperature',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='country_data',
            name='average_temperature_uncertainty',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='state_data',
            name='average_temperature',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='state_data',
            name='average_temperature_uncertainty',
            field=models.CharField(max_length=10),
        ),
    ]
