# Generated by Django 4.1.7 on 2023-03-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_data', '0006_alter_city_data_average_temperature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State_average',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_temperature', models.CharField(max_length=10)),
                ('average_temperature_uncertainty', models.CharField(max_length=10)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temperature_data.country')),
            ],
        ),
        migrations.CreateModel(
            name='Country_average',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_temperature', models.CharField(max_length=10)),
                ('average_temperature_uncertainty', models.CharField(max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temperature_data.country')),
            ],
        ),
        migrations.CreateModel(
            name='City_average',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_temperature', models.CharField(max_length=10)),
                ('average_temperature_uncertainty', models.CharField(max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temperature_data.country')),
            ],
        ),
    ]
