# Generated by Django 4.1.7 on 2023-03-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_data', '0007_state_average_country_average_city_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_average',
            name='average_temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='city_average',
            name='average_temperature_uncertainty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='country_average',
            name='average_temperature',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='country_average',
            name='average_temperature_uncertainty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='state_average',
            name='average_temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='state_average',
            name='average_temperature_uncertainty',
            field=models.FloatField(),
        ),
    ]
