# Generated by Django 4.1.7 on 2023-03-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_data', '0009_alter_city_average_city_alter_state_average_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_average',
            name='latitude',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='city_average',
            name='longitude',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
